### ISSUE TITLE
Improve the design for input box

### ISSUE THREAD

**Issue by pulkit-30** [pulkit-30/React-Keeper-App#2]
Improve the design of the Input box and add animation.
Hide the note input box and only display it when the user wants to add a new note. 

<img width="790" alt="Screenshot 2021-10-06 at 9 42 01 PM" src="https://user-images.githubusercontent.com/76155456/136242774-73e5e36c-b64a-4425-8f7b-83a3796976ee.png">

**Comment by AkshayMathurr** [comment]
Hi, Can I take this up ?

**Comment by markandey007** [comment]
I am taking this up.

**Comment by pulkit-30** [comment]
@AkshayMathurr  you can go for it
