### ISSUE TITLE
Fix the empty form submission

### ISSUE THREAD

**Issue by pulkit-30** [pulkit-30/React-Keeper-App#3]
The empty form should not submit.
At present, the empty form is submitted that results in empty and unnecessary cards.

<img width="1677" alt="Screenshot 2021-10-06 at 10 15 48 PM" src="https://user-images.githubusercontent.com/76155456/136247936-6e998def-41da-4b34-b32a-abd2d3cc4c71.png">

**Comment by AkshayMathurr** [comment]
Can I take this up?

**Comment by markandey007** [comment]
Taking this up
